TYPO3:
  TypoScript:
    rendering:
      exceptionHandler: 'TYPO3\TypoScript\Core\ExceptionHandlers\ThrowingHandler'
    enableContentCache: FALSE

    # Register an additional prefixed helper for functional tests
    defaultContext:
      'Testing.String': 'TYPO3\Eel\Helper\StringHelper'
