TYPO3:
  TypoScript:
    rendering:
      exceptionHandler: 'Neos\Fusion\Core\ExceptionHandlers\ThrowingHandler'
    enableContentCache: FALSE

    # Register an additional prefixed helper for functional tests
    defaultContext:
      'Testing.String': 'Neos\Eel\Helper\StringHelper'
      'Testing.Utility': 'Neos\Fusion\Tests\Functional\TypoScriptObjects\Fixtures\Helper\UtilityHelper'
